# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EstimateAutomation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks	
	pod 'AeroGearOAuth2'
  use_frameworks!

  # Pods for EstimateAutomation

  target 'EstimateAutomationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EstimateAutomationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
